name: CI
on: push
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Test
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Initialize environment
        run: just init-venv

      - name: Test
        run: just test

  build:
    name: Build
    needs: [test]
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.11"]
    runs-on: ${{ matrix.os }}
    if: contains(github.ref, 'refs/heads/release/') == false && startsWith(github.ref, 'refs/tags/') == false
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Initialize environment
        run: just init-venv

      - name: Build
        run: just build

  verify-release:
    name: Verify Release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/heads/release/')
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Initialize environment
        run: just init-venv

      - name: Check if tag exists
        run: just check-if-tag-exists

  deploy:
    name: Deploy
    timeout-minutes: 10
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Initialize environment
        run: just init-venv

      - name: Create PyPi configuration file
        run: |
          rm -rf ~/.pypirc
          touch ~/.pypirc
          echo "[pypi]
          username = __token__
          password = ${{ secrets.PYPI_TOKEN }}" >> ~/.pypirc

      - name: Upload
        run: just upload
